apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vm-app-project
  namespace: openshift-gitops
spec:
  description: VM gitops
  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
