apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: sno1
data:
  .dockerconfigjson: <add encoded base64 pull-secret> 
  # base64 <<< "your_string" to encode 
  # base64 -D <<< "your_encoded_string" to decode
type: kubernetes.io/dockerconfigjson