# example-node1-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace example-sno
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "sno1"
  namespace: "sno1"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  baseDomain: "cotton.blue"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.16.9-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD2Sh84/z9jj4Neg4xI3jlPO6C8sLdz3ykJjo+vD+WveOSBql2LiJ1k4z/AcBC55/ZPfZt6oK1pqtHYTIcZLobH7ApHvRSdsDmVgh67u/Lx5XMZ5ct6O9jC+lp98vNjGP5c9Zfcn1zIzcPATleOS52ubGQJA58ryuckoEq6TyyfvcHjUMNBv7AULDQ68syv0i9tuS+SH9cUgaEQGHsTyL9wA5fudh2JpLMvZigE0KqAwP/Z91QLyMFZsuxoy7x0CFBFym4miXiF7gVSpYsJxcUbb6qRSeHi4PGhNBm3IytRcbTOrwcdCx2E2uiyuWliC85NtMslQHYy+8eXcUavSW3GZnxgjenUnaNAIhQ1GQdUAdRmsLCzRehzBi/i3mc4ZgkhODQHacCg14RKj7c5GgyAh3b/6M9D43sqrjZa2vH1+RwID9wgWngVjJmy/RZ3tIhT94GKUn4/AWfAUpAtM1c3C1sxqRFTk6Q9otYm1Qq95/V0ewBQnbuzkpJSlCjtNqM= mabe@mabe.remote.csb"
  clusters:
  - clusterName: "sno1"
    networkType: "OVNKubernetes"
    extraManifests:
      filter:
        inclusionDefault: exclude
    clusterLabels:
      regional-hub: "true"
      sites : "sno1"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.1.0/24
    serviceNetwork:
      - 172.30.0.0/16
    additionalNTPSources:
      - clock.redhat.com
    # proxy:
    #   # httpProxy: http://117.252.9.178:3128
    #   # httpsProxy: http://117.252.9.178:3128
    #   noProxy: .cotton.blue
    crTemplates:
     KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    nodes:
      - hostName: "sno1"
        role: "master"
        # bmcAddress: "ilo4-virtualmedia://192.168.1.62/redfish/v1/Systems/1"
        bmcAddress: "redfish-virtualmedia://fakefish-192-168-1-62-fakefish.apps.sno3.cotton.blue/redfish/v1/Systems/1"
        # bmcAddress: "ilo4-virtualmedia://fakefish-192-168-1-62-fakefish.apps.hub.cotton.blue/redfish/v1/Systems/1"
        bmcCredentialsName:
          name: "sno-bmc-secret"
        bootMACAddress: "98:f2:b3:ed:9e:58"
        bootMode: "UEFI"
        rootDeviceHints:
          wwn: 0x600508b1001c6f8c8d556fd234f32781
          # deviceName: /dev/sda
          # deviceName: "/dev/disk/by-path/pci-0000:0a:00.0-scsi-0:1:0:1"
          # serialNumber: 3600508b1001c152315a9ff023826e090
          # serialNumber: S3L1BTL80000N530A26J
        nodeNetwork:
          interfaces:
            - name: "ens1s0"
              macAddress: "98:f2:b3:ed:9e:58"
            - name: "ens1f0np0"
              macAddress: "b8:59:9f:de:72:20"
            - name: "ens1f1np1"
              macAddress: "b8:59:9f:de:72:21"
          config:
            interfaces:
              - name: ens1s0
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  dhcp: false
                  address:
                  - ip: 192.168.1.170
                    prefix-length: 24
              - name: ens1f0np0
                type: ethernet
                state: down
                ipv4:
                  enabled: false
                  dhcp: false
              - name: ens1f1np1
                type: ethernet
                state: down
                ipv4:
                  enabled: false
                  dhcp: false
            dns-resolver:
               config:
                 search:
                 - cotton.blue
                 server:
                 - 192.168.1.1
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: ens1s0
                next-hop-address: 192.168.1.1
                table-id: 254

