# example-node1-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace example-sno
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "sno1"
  namespace: "sno1"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  baseDomain: "dinesh154.dfw.ocp.run"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "openshift-v4.17.17"
  sshPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJn0yUIqXBCIglm0UUA+qLF+Dlr5U9pneFLOFdt+f9XJ dlakshma@redhat.com"
  clusters:
  - clusterName: "sno1"
    networkType: "OVNKubernetes"
    extraManifests:
      filter:
        inclusionDefault: exclude
    clusterLabels:
      #regional-hub: "true"
      sites : "sno1"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.1.0/24
    serviceNetwork:
      - 172.30.0.0/16
    additionalNTPSources:
      - clock.redhat.com
    # proxy:
    #   # httpProxy: http://117.252.9.178:3128
    #   # httpsProxy: http://117.252.9.178:3128
    #   noProxy: .cotton.blue
    crTemplates:
     KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    nodes:
      - hostName: "sno1"
        role: "master"
        # bmcAddress: "ilo4-virtualmedia://192.168.1.62/redfish/v1/Systems/1"
        # bmcAddress: "idrac-virtualmedia+https://192.168.110.118/redfish/v1/Systems/System.Embedded.1"
        bmcAddress: "idrac-virtualmedia://192.168.110.118/redfish/v1/Systems/System.Embedded.1"
        #bmcAddress: "redfish-virtualmedia://fakefish-192-168-1-62-fakefish.apps.sno3.cotton.blue/redfish/v1/Systems/1"
        # bmcAddress: "ilo4-virtualmedia://fakefish-192-168-1-62-fakefish.apps.hub.cotton.blue/redfish/v1/Systems/1"
        bmcCredentialsName:
          name: "sno-bmc-secret"
        bootMACAddress: "d0:8e:79:ed:6c:90"
        bootMode: "UEFI"
        rootDeviceHints:
          # wwn: 0x600508b1001c6f8c8d556fd234f32781
          #deviceName: /dev/sda
          # deviceName: "/dev/disk/by-path/pci-0000:0a:00.0-scsi-0:1:0:1"
          # serialNumber: 3600508b1001c152315a9ff023826e090
          # serialNumber: S3L1BTL80000N530A26J          
          #### below device represents Dell Node18 
          #deviceName: /dev/nvme0n1
          #wwn: eui.ace42e00162c876f
          deviceName: "/dev/disk/by-path/pci-0000:b1:00.0-nvme-1"
        nodeNetwork:
          interfaces:
            - name: "eno8303"
              macAddress: "d0:8e:79:ed:6c:90"
            #- name: "en08403"
            #  macAddress: "d0:8e:79:ed:6c:91"
            #- name: "enp202s0"
            #  macAddress: "40:a6:b7:7c:8e:b8"
          config:
            interfaces:
              - name: eno8303
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  dhcp: false
                  address:
                  - ip: 192.168.154.118
                    prefix-length: 24
              #- name: en08403
              #  type: ethernet
              #  state: down
              #  ipv4:
              #    enabled: false
              #    dhcp: false
              #- name: enp202s0
              #  type: ethernet
              #  state: down
              #  ipv4:
              #    enabled: false
              #    dhcp: false
            dns-resolver:
               config:
                 search:
                 - "dinesh154.dfw.ocp.run"
                 server:
                 - 192.168.154.10
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: ens1s0
                next-hop-address: 192.168.154.1
                table-id: 254

