apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
  namespace: open-cluster-management
spec:
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
    storageClassName: ocs-storagecluster-ceph-rbd
    #storageClassName: lvms-vg1-immediate
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 80Gi
    storageClassName: ocs-storagecluster-ceph-rbd
    #storageClassName: lvms-vg1-immediate
  imageStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
    storageClassName: ocs-storagecluster-ceph-rbd
    #storageClassName: lvms-vg1-immediate  
  osImages:
  - openshiftVersion: "4.17"
    cpuArchitecture: x86_64
    rootFSUrl: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.17/4.17.17/rhcos-4.17.17-x86_64-live-rootfs.x86_64.img
    url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.17/4.17.17/rhcos-4.17.17-x86_64-live.x86_64.iso
    version: 4.17.7
  - openshiftVersion: "4.18"
    cpuArchitecture: x86_64
    rootFSUrl: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.18/4.18.1/rhcos-4.18.1-x86_64-live-rootfs.x86_64.img
    url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.18/4.18.1/rhcos-4.18.1-x86_64-live.x86_64.iso
    version: 4.18.1